Dont modifiy check_mk files

diff --git a/check_mk_agent b/check_mk_agent
--- a/check_mk_agent
+++ b/check_mk_agent
@@ -93,7 +93,7 @@ function run_cached () {
     # Check if cache file exists and is recent enough
     if [ -s "$CACHEFILE" ] ; then
         local MTIME=$(stat -c %Y "$CACHEFILE")
-        if [ $((NOW - MTIME)) -le "$MAXAGE" ] ; then local USE_CACHEFILE=1 ; fi
+        if [ $((NOW - MTIME)) -le $MAXAGE ] ; then local USE_CACHEFILE=1 ; fi
         # Output the file in any case, even if it is
         # outdated. The new file will not yet be available
         cat "$CACHEFILE"
@@ -135,12 +135,12 @@ echo '<<<df>>>'
 # The exclusion list is getting a bit of a problem. -l should hide any remote FS but seems
 # to be all but working.
 excludefs="-x smbfs -x cifs -x iso9660 -x udf -x nfsv4 -x nfs -x mvfs -x zfs"
-df -PTlk "$excludefs" | sed 1d
+df -PTlk $excludefs | sed 1d
 
 # df inodes information
 echo '<<<df>>>'
 echo '[df_inodes_start]'
-df -PTli "$excludefs" | sed 1d
+df -PTli $excludefs | sed 1d
 echo '[df_inodes_end]'
 
 # Filesystem usage for ZFS
@@ -165,7 +165,7 @@ then
         sed 's/\\040/ /g' |
         while read MP
 	do
-	 if [ "$STAT_VERSION" != $STAT_BROKE ]; then
+	 if [ $STAT_VERSION != $STAT_BROKE ]; then
 	    waitmax -s 9 2 stat -f -c "$MP ok %b %f %a %s" "$MP" || \
 		echo "$MP hanging 0 0 0 0"
 	 else
@@ -179,7 +179,7 @@ then
         sed 's/\\040/ /g' |
         while read MP
         do
-         if [ "$STAT_VERSION" != $STAT_BROKE ]; then
+         if [ $STAT_VERSION != $STAT_BROKE ]; then
             waitmax -s 9 2 stat -f -c "$MP ok %b %f %a %s" "$MP" || \
                 echo "$MP hanging 0 0 0 0"
          else
@@ -219,8 +219,8 @@ then
     for eth in $(sed -e 1,2d < /proc/net/dev | cut -d':' -f1 | sort)
     do
         echo "[$eth]"
-        ethtool "$eth" | egrep '(Speed|Duplex|Link detected|Auto-negotiation):'
-        echo -en "\tAddress: " ; cat /sys/class/net/"$eth"/address ; echo
+        ethtool $eth | egrep '(Speed|Duplex|Link detected|Auto-negotiation):'
+        echo -en "\tAddress: " ; cat /sys/class/net/$eth/address ; echo
     done
 fi
 
@@ -228,7 +228,7 @@ fi
 # Current state of bonding interfaces
 if [ -e /proc/net/bonding ] ; then
     echo '<<<lnx_bonding:sep(58)>>>'
-    pushd /proc/net/bonding > /dev/null || exit ; head -v -n 1000 * ; popd || exit
+    pushd /proc/net/bonding > /dev/null ; head -v -n 1000 * ; popd
 fi
 
 # Same for Open vSwitch bonding
@@ -236,7 +236,7 @@ if type ovs-appctl > /dev/null ; then
     echo '<<<ovs_bonding:sep(58)>>>'
     for bond in $(ovs-appctl bond/list | sed -e 1d | cut -f2) ; do
         echo "[$bond]"
-        ovs-appctl bond/show "$bond"
+        ovs-appctl bond/show $bond
     done
 fi
 
@@ -293,7 +293,7 @@ then
     # At least with ipmi-sensoirs 0.7.16 this group is Power_Unit instead of "Power Unit"
     run_cached -s ipmi_sensors 300 "for class in Temperature Power_Unit Fan
     do
-        ipmi-sensors $IPMI_FORMAT --sdr-cache-directory /var/cache -g ""$class"" | sed -e 's/ /_/g' -e 's/:_\?/ /g' -e 's@ \([^(]*\)_(\([^)]*\))@ \2_\1@'
+        ipmi-sensors $IPMI_FORMAT --sdr-cache-directory /var/cache -g "$class" | sed -e 's/ /_/g' -e 's/:_\?/ /g' -e 's@ \([^(]*\)_(\([^)]*\))@ \2_\1@'
         # In case of a timeout immediately leave loop.
         if [ $? = 255 ] ; then break ; fi
     done"
@@ -315,8 +315,8 @@ then
     DISKS=$(echo "$DMSTATUS" | cut -f1 -d\:)
 
     for disk in $DISKS ; do
-        device=$(cat /sys/block/$(basename "$disk")/device/model )
-        status=$(echo "$DMSTATUS" | grep ^"${disk}")
+        device=$(cat /sys/block/$(basename $disk)/device/model )
+        status=$(echo "$DMSTATUS" | grep ^${disk})
         echo "$status Model: $device"
     done
 fi
@@ -343,8 +343,8 @@ if [ "$MegaCli_bin" != "unknown" ]; then
     echo '<<<megaraid_pdisks>>>'
     for part in $($MegaCli_bin -EncInfo -aALL -NoLog < /dev/null \
         | sed -rn 's/:/ /g; s/[[:space:]]+/ /g; s/^ //; s/ $//; s/Number of enclosures on adapter ([0-9]+).*/adapter \1/g; /^(Enclosure|Device ID|adapter) [0-9]+$/ p'); do
-        [ "$part" = adapter ] && echo ""
-        [ "$part" = 'Enclosure' ] && echo -ne "\ndev2enc"
+        [ $part = adapter ] && echo ""
+        [ $part = 'Enclosure' ] && echo -ne "\ndev2enc"
         echo -n " $part"
     done
     echo
@@ -359,11 +359,11 @@ fi
 if type tw_cli > /dev/null ; then
     for C in $(tw_cli show | awk 'NR < 4 { next } { print $1 }'); do
         echo '<<<3ware_info>>>'
-        tw_cli /"$C" show all | egrep 'Model =|Firmware|Serial'
+        tw_cli /$C show all | egrep 'Model =|Firmware|Serial'
         echo '<<<3ware_disks>>>'
-        tw_cli /"$C" show drivestatus | egrep 'p[0-9]' | sed "s/^/$C\//"
+        tw_cli /$C show drivestatus | egrep 'p[0-9]' | sed "s/^/$C\//"
         echo '<<<3ware_units>>>'
-        tw_cli /"$C" show unitstatus | egrep 'u[0-9]' | sed "s/^/$C\//"
+        tw_cli /$C show unitstatus | egrep 'u[0-9]' | sed "s/^/$C\//"
     done
 fi
 
@@ -379,7 +379,7 @@ fi
 echo '<<<vbox_guest>>>'
 if type VBoxControl >/dev/null 2>&1 ; then
     VBoxControl -nologo guestproperty enumerate | cut -d, -f1,2
-    [ "${PIPESTATUS[0]}" = 0 ] || echo "ERROR"
+    [ ${PIPESTATUS[0]} = 0 ] || echo "ERROR"
 fi
 
 # OpenVPN Clients. Currently we assume that the configuration # is in
@@ -424,9 +424,9 @@ if type lpstat > /dev/null 2>&1; then
             LOCAL_PRINTERS=$(grep -E "<(Default)?Printer .*>" $CPRINTCONF | awk '{print $2}' | sed -e 's/>//')
             lpstat -p | while read LINE
             do
-                PRINTER=$(echo "$LINE" | awk '{print $2}')
+                PRINTER=$(echo $LINE | awk '{print $2}')
                 if echo "$LOCAL_PRINTERS" | grep -q "$PRINTER"; then
-                    echo "$LINE"
+                    echo $LINE
                 fi
             done
             echo '---'
@@ -434,7 +434,7 @@ if type lpstat > /dev/null 2>&1; then
             do
                 PRINTER=${LINE%%-*}
                 if echo "$LOCAL_PRINTERS" | grep -q "$PRINTER"; then
-                    echo "$LINE"
+                    echo $LINE
                 fi
             done
         else
@@ -458,11 +458,11 @@ if type cl_status > /dev/null 2>&1; then
 
   echo '<<<heartbeat_nodes>>>'
   for NODE in $(cl_status listnodes); do
-    if [ "$NODE" != $(echo "$HOSTNAME" | tr 'A-Z' 'a-z') ]; then
-      STATUS=$(cl_status nodestatus "$NODE")
+    if [ $NODE != $(echo $HOSTNAME | tr 'A-Z' 'a-z') ]; then
+      STATUS=$(cl_status nodestatus $NODE)
       echo -n "$NODE $STATUS"
-      for LINK in $(cl_status listhblinks "$NODE" 2>/dev/null); do
-        echo -n " $LINK $(cl_status hblinkstatus "$NODE" "$LINK")"
+      for LINK in $(cl_status listhblinks $NODE 2>/dev/null); do
+        echo -n " $LINK $(cl_status hblinkstatus $NODE $LINK)"
       done
       echo
     fi
@@ -484,11 +484,11 @@ fi
 if type postconf >/dev/null ; then
     echo '<<<postfix_mailq>>>'
     postfix_queue_dir=$(postconf -h queue_directory)
-    postfix_count=$(find "$postfix_queue_dir"/deferred -type f | wc -l)
-    postfix_size=$(du -ks "$postfix_queue_dir"/deferred | awk '{print $1 }')
-    if [ "$postfix_count" -gt 0 ]
+    postfix_count=$(find $postfix_queue_dir/deferred -type f | wc -l)
+    postfix_size=$(du -ks $postfix_queue_dir/deferred | awk '{print $1 }')
+    if [ $postfix_count -gt 0 ]
     then
-       echo -- "$postfix_size" Kbytes in "$postfix_count" Requests.
+       echo -- $postfix_size Kbytes in $postfix_count Requests.
     else
        echo Mail queue is empty
     fi
@@ -537,7 +537,7 @@ then
     do
         if [ -S "/omd/sites/$site/tmp/run/live" ] ; then
             echo "[$site]"
-            echo -e "GET status" | waitmax 3 /omd/sites/"$site"/bin/unixcat /omd/sites/"$site"/tmp/run/live
+            echo -e "GET status" | waitmax 3 /omd/sites/$site/bin/unixcat /omd/sites/$site/tmp/run/live
         fi
     done
 fi
@@ -555,7 +555,7 @@ if pushd $MK_VARDIR/job >/dev/null; then
             cd ..
         fi
     done
-    popd > /dev/null || exit
+    popd > /dev/null
 fi
 
 # Gather thermal information provided e.g. by acpi
@@ -564,8 +564,8 @@ if ls /sys/class/thermal/thermal_zone* >/dev/null 2>&1; then
     echo '<<<lnx_thermal>>>'
     for F in /sys/class/thermal/thermal_zone*; do
         echo -n "${F##*/} "
-        if [ ! -e "$F"/mode ] ; then echo -n "- " ; fi
-        cat "$F"/{mode,type,temp,trip_point_*} | tr \\n " "
+        if [ ! -e $F/mode ] ; then echo -n "- " ; fi
+        cat $F/{mode,type,temp,trip_point_*} | tr \\n " "
         echo
     done
 fi
@@ -596,13 +596,13 @@ echo '<<<local>>>'
 if cd $LOCALDIR ; then
     for skript in $(ls) ; do
         if [ -f "$skript" -a -x "$skript" ] ; then
-            ./"$skript"
+            ./$skript
         fi
     done
     # Call some plugins only every X'th minute
     for skript in [1-9]*/* ; do
         if [ -x "$skript" ] ; then
-            run_cached local_"${skript//\//\\}" "${skript%/*}" "$skript"
+            run_cached local_${skript//\//\\} ${skript%/*} "$skript"
         fi
     done
 fi
@@ -611,13 +611,13 @@ fi
 if cd $PLUGINSDIR ; then
     for skript in $(ls) ; do
         if [ -f "$skript" -a -x "$skript" ] ; then
-            ./"$skript"
+            ./$skript
         fi
     done
     # Call some plugins only every Xth minute
     for skript in [1-9]*/* ; do
         if [ -x "$skript" ] ; then
-            run_cached plugins_"${skript//\//\\}" "${skript%/*}" "$skript"
+            run_cached plugins_${skript//\//\\} ${skript%/*} "$skript"
         fi
     done
 fi
@@ -625,7 +625,7 @@ fi
 # Agent output snippets created by cronjobs, etc.
 if [ -d "$SPOOLDIR" ]
 then
-    pushd "$SPOOLDIR" > /dev/null || exit
+    pushd "$SPOOLDIR" > /dev/null
     now=$(date +%s)
 
     for file in *
@@ -647,7 +647,7 @@ then
         # If there is at least one digit, than we honor that.
         if [ "$maxage" ] ; then
             mtime=$(stat -c %Y "$file")
-            if [ $((now - mtime)) -gt "$maxage" ] ; then
+            if [ $((now - mtime)) -gt $maxage ] ; then
                 continue
             fi
         fi
@@ -655,5 +655,5 @@ then
         # Output the file
         cat "$file"
     done
-    popd > /dev/null || exit
+    popd > /dev/null
 fi
